### ISSUE TITLE
Add an API to manipulate a Sequence Diagram

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/papyrus-seqd#14]
The API should contain all the (non-trivial) actions required to create and edit a sequence diagrams: creation/deletion of elements (Lifeline, Messages, InteractionUse...), reordering of messages/fragments, ...

Note that trivial actions (Such as renaming an element) are not covered, as we can edit the UML Element directly. The API should expose actions which might require a more complex sequence of actions (Such as: creation of a message -> also create the Message Ends, insert them at the right location, ...)

**Comment by CamilleLetavernier** [comment]
It's still unclear on the Wiki whether the API should be based on Semantic Elements, visual Elements, Hybrid elements (Logical model/Facade), or any of these (Semantic + optional Visual element).

Since the diagram representation is initially derived from the Semantic Model, then annotated with visual deltas, and because I don't think we have a real logical model, using the semantic element seems to make more sense: the API can then be used on a plain semantic model, as well as from a Diagram. Visual annotations can be added in a second step. For example, when creating a Message, we simply indicate where it should be inserted (Before/After/Between), and it is created with a default position delta (e.g. 20px below the previous message / 20 px above the next), shifting the layout as necessary. Then, if the user wants, he may move the message by adding a delta (+/- X pixels), which won't affect the semantics.

This makes sense because when we add a message, we don't want it to be placed exactly where the user puts it; but we want to insert it between two existing messages (Or before/after other messages), regardless of the actual final layout.

So the API would only handle semantic elements, an index-based insertion point, and the diagram would be derived from the result of the semantic changes.

This means that this API wouldn't be responsible for modifying the "visual deltas" (e.g. Increase the gap between occurrences specifications).

The API would look like this:

- createX(params)
- delete(X) [A single delete method for all elements, unless we need specific parameters]
- retargetX(params): typically to retarget messages. More generally, we need one such method for each connector (Message, Comment link, Duration constraint...)
- moveX(params): similar to retarget, but for nodes (Occurence specifications/Execution specifications)

Since all these methods return a command, these methods include the canExecute() behavior. However, we still need a "partial" canExecute for edges, because we need partial feedback (Creating an edge from the palette is typically a 2-steps process: first decide the source, then decide the target. We only get a createCommand when both the source and target are known, but we still need feedback to determine whether the source is valid for this edge). This may be covered with an additional "isPossibleXSource" for each X connector to create (e.g. isPossibleMessageSource(sourceElement, messageSort))

**Comment by acampesino** [comment]
I disagree with various of the statement there. We actually want to set the message exactly in the position the user create it, exactly where the visual feedback has shown him/her how the result of the operation will be.

The semantical model provides the the element ordering constraint but nothing about the specific position of element in the diagram, so both part are needed. Now, if the visual position information contradict the semantical ordering, a recover mechanism should be able to provide a compatible visual position of elements that fulfill the semantical order.

The API does not need to provide commands, it could just perform the actions to be executed by the command, so the commands execution delegate to the API. In that way we decouple the API from the policies / command infrastructure and allow to provide API that can be used without commands.

I cannot see how the API, will facilitate or provide the support for visual feedbacks and constraints so whoever use the API can come with that information.

One of the problem with the current implementation is that edge moving is implemented by retargeting the source and target anchors, which make impossible for the API to distinguish between moving / reorder the messages or changing message endpoints or changing from horizontal messages to delayed received messages (target height > src height)

Many of the functions has element as parameters, such as createExecutionSpecification(Element e). That means e is the lifeline? e is the message triggering the execution specification?

The approach should be handle the messages as nodes (with the constraint that only moves vertically). The API should be defined with messages in mind, and with the UML specification in mind, not just a delegation of the current GMF infrastructure, otherwise it will not provide much additional value.

I don't see either how the API will handle the inherent element groups (synch message and the execution spec that triggers, and all the messages that originate in that exec spec). And that it is one of the most important aspect, as those groups needs to be handle as one element, move together, reorder together, delete in cascade, and the correspondent visual feedbacks needs to be provided with the limits of the group.

**Comment by planger** [comment]
Doing a scrub on open issues, I'm closing this, as the purpose of this ticket was discussion and we settled on an API for manipulating sequence diagrams via the logical model.
