### ISSUE TITLE
Do not move message when the user shifts message ends

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#323]
When moving a message end, the opposite message end is currently shifted automatically to prevent an upwards slope.

Now as we can move messages nicely by grabbing them anywhere on the line (see #310), I think it would be better to just forbid moving the "receive end" before the "send end" altogether and stop shifting the "send end" of the message up to prevent an upwards slope when moving the receive end and vice versa.

This would make it simpler and more clear: want to move the message? Just grab it in the middle. Want to change the slope? Grab it at an end handle and do so, but you can't create a forbidden upwards pointing slope. Currently it is sort of a hybrid, as you can also move the message indirectly by changing the slope.

**Comment by cdamus** [comment]
The discussion here addresses asynchronous messages that may be sloped.  But should we apply the same restriction to messages that must be horizontal (e.g., synchronous calls, replies)?  I would expect so, because moving either end must not result in the message connection sloping in either direction, so currently the other end tracks the motion, but I think that for consistency with the asynchronous messages we would not want that.

**Comment by cdamus** [comment]
This seems to have been implemented already in the master branch by other fixes, both for asynchronous and for synchronous messages.
