### ISSUE TITLE
Nudge of elements on unrelated lifelines after insertion

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#356]
We've decided that also elements on unrelated lifelines should be nudged and this already is implemented for _deletions_. However, it doesn't work across all scenarios for _insertions_ of new fragments.

Consider for instance the interaction below:
![image](https://user-images.githubusercontent.com/588090/45623469-c1d34580-ba87-11e8-9807-2c357998f0ff.png)

If I now add a new execution of `Lifeline3` above the send and receive events of the two existing messages, I'd expect them to be nudged down, however they aren't:
![image](https://user-images.githubusercontent.com/588090/45623521-ec250300-ba87-11e8-8e26-e61648cd9e35.png)

Fortunately, they are sorted in correctly in the semantic model though:
![image](https://user-images.githubusercontent.com/588090/45623561-124aa300-ba88-11e8-8635-fbd111395e10.png)

If there would be a message from `Lifeline2` --> `Lifeline3` before the existing messages, nudging would work as expected.

**Comment by cdamus** [comment]
Yes.  I think the insertion uses the causal dependency graph, in which other lifelines can be on branches that aren't visited.  I suppose we'll need to use the global interaction-fragment ordering to find all of the elements to be nudged.

**Comment by planger** [comment]
Not sure yet, I've only briefly started testing in detail with that scenario and found that it seems to work fine, when a second execution is added above the first on `Lifeline3`, even though they are still not directly connected. So it might be that 8d94a7c3f145b5da462695af8b669c480548a87e wasn't enough to address all usecases.

**Comment by planger** [comment]
As mentioned by @jfaltermeier there is another instance of this issue as detailed in the second point of the first review comment in #357 and in the following (copied from #357 for convenience):

> It seems only the receive event is moved to make space when adding a new message above a sloped async message
> ![image](https://user-images.githubusercontent.com/588090/45743072-9cffdf00-bbfb-11e8-80c3-2536e7f98ac1.png)
> leads to the following even though I left space before the send event of the async message when creating the sync message
> ![image](https://user-images.githubusercontent.com/588090/45743100-a8eba100-bbfb-11e8-8d88-0c94bc7e0dc6.png)

Comment from @jfaltermeier: 
> The second point seems to have the same or a similar cause as #356
The sloped message start is not found as the following element, because getTarget()#following is used.

**Comment by cdamus** [comment]
As of commit 0629e51d48bd1df7a915fa962503493964a4025e at the latest, I see the expected nudging in both cases documented in this issue:

* inserting an execution occurrence on an otherwise unconnected lifeline nudges down messages that follow it in the timeline
* inserting a synchronous message above an asynchronous message oriented in the other direction, the asynchronous message and the existing synchronous message below it are nudged down.  The slope of the asynchronous message is not changed; both ends are nudged

However, I do observe that when I create the initial configuration of the second scenario (from 357), the insertion of the asynchronous message above the synchronous message *doesn't nudge the synchronous message*.  I think that's the correct behaviour because in constructing the sequence diagram I left a lot of room for the synchronous message, so there was no need to nudge anything.

In fact, both of these scenarios are fixed by commit 0629e51d48bd1df7a915fa962503493964a4025e for issue #26.  So, this issue is closed.  Please re-open if there are other scenarios not accounted for.
