### ISSUE TITLE
Nudging of ExecSpec is sometimes too long

### ISSUE THREAD

**Issue by rschnekenbu** [eclipsesource/papyrus-seqd#388]
During sprint demo, I encountered an issue with the size of an exec spec. The exec spec was expanded too much when creating a self sync message on another lifeline in the timeline between the start and the finish of the exec spec.

**Comment by rschnekenbu** [comment]
here is the demo model.
Steps to reproduce:
- [] Create an exec spec on lifeline2 (type_p1:xxx) at the bottom of the diagram
- [] Create a self sync message on the Lifeline 3 (L3_As_Test), start and end of the message should be vertically placed between start and finish of the created exec spec on step 1.
- [] exec spec of step 1 is nudged, but it is way too big.

**Comment by jfaltermeier** [comment]
The problem is that the the message nudge logic takes the send offset directly into account.
In above example we have a big offset on Lifeline 3, so the ExecSpec end is nudged quite heavily. 
If you insert a further ExecSpec on Lifeline 3 before the new one on Lifeline 2, and then create the message, the nuding is much smaller, because the send offset is smaller.

**Comment by rschnekenbu** [comment]
PR #391 was merged, fixing and testing this issue. closing task.
