### ISSUE TITLE
[Message:014]: Create creation message

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#46]
A creation message SHALL be created (Palette or assistant) by providing the source (send event) and target (receive event) points. If the receive event location is the top most in the lifeline, the head of the lifeline SHALL be shift down so the middle point of the head correspond with the intended receive event location and the message will be created between the send event location or the closest one than does not contradict any other requirement, and the middle point of the left or right side of the lifeline head, choosing the closest one to the send location. Otherwise the message will be created between these points, or the closest ones than does not contradict any other requirement.

**Comment by jfaltermeier** [comment]
@acampesino 
My current development allows the creation of creation messages and shifting down the lifeline when the receive event location is the topmost element in the lifeline. 
![1](https://user-images.githubusercontent.com/5889696/42262123-9367c41c-7f6a-11e8-842b-fd3c1cbdcf69.png)
![2](https://user-images.githubusercontent.com/5889696/42262128-97c52284-7f6a-11e8-9c7e-04921f0e5916.png)

I wanted to clarify the requirements here for the cases where the receive event location is not the topmost element in the lifeline. Currently we disallow the creation when the receive event location is not the first element. Is this expected behaviour here or should we create the message here like any other message without shifting the lifeline down? 
![3](https://user-images.githubusercontent.com/5889696/42262133-9bb5d14a-7f6a-11e8-9a13-ab82c12cbc6f.png)
![4](https://user-images.githubusercontent.com/5889696/42262135-9e18cdde-7f6a-11e8-90bb-2b58c7cebac0.png)

**Comment by acampesino** [comment]
@jfaltermeier I will say you create the create message, and the lifeline header is shift down to be anchored to the first message if and only if it is a create message. 
That behavior must be enforced whenever a create message receive event becomes the first ocurrence in the lifeline.
